#!/opt/local/bin/ruby

def change_log(stream)
  ActiveRecord::Base.logger = Logger.new(stream)
  ActiveRecord::Base.clear_active_connections!
  reload!
end
 
def show_log
  change_log(STDOUT)
end
 
def hide_log
  change_log(nil)
end

class Object
  def error_messages
    if self.respond_to?(:errors)
      if self.errors.full_messages.any?
        puts '', 'The following errors were found:', '=' * 75
        self.errors.full_messages.each do |msg|
          puts "  #{msg}"
        end
        puts ''
        self.details
      end
    end
  end
  alias :em :error_messages
  
  def details
    if self.respond_to?(:attributes) and self.attributes.any?
      max = self.attributes.keys.map { |a| a.length }.sort.pop + 5
      puts '', "Details for the #{self.class} are:", '=' * 75
      puts sprintf("%-#{max}.#{max}s%-15.15s", "id", self.id)
      self.attributes.keys.sort.each do |k|
        next if %w(id created_at updated_at).include?(k.to_s)
        puts sprintf("%-#{max}.#{max}s%s", k, (self.try(k).blank? ? 'null' : self[k]))
      end
      %w(created_at updated_at).each do |k|
        puts sprintf("%-#{max}.#{max}s%s", k, self[k.to_sym])
      end
      puts ''
    end
  end
  
end